# Generated by Django 4.1.5 on 2023-02-26 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0007_expert"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expert_Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("has_answer", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name="expert",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expert_category",
                to="pybo.expert_category",
            ),
        ),
    ]
