# Generated by Django 4.1.5 on 2023-03-08 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pybo", "0009_post_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expert_answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modify_date", models.DateTimeField(blank=True, null=True)),
                ("content", models.TextField()),
                ("create_date", models.DateTimeField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expert_author_answer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pybo.expert"
                    ),
                ),
                (
                    "voter",
                    models.ManyToManyField(
                        related_name="expert_voter_answer", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
