# Generated by Django 4.1.5 on 2023-03-19 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0012_pet"),
    ]

    operations = [
        migrations.AddField(
            model_name="expert",
            name="pet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pet",
                to="pybo.pet",
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="photo",
            field=models.ImageField(null=True, upload_to="photos/%Y/%m/%d/"),
        ),
    ]
