# Generated by Django 4.1.5 on 2023-03-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0013_expert_pet_alter_pet_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="expert",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to="photos/%Y/%m/%d/"),
        ),
    ]
