# Generated by Django 4.1.5 on 2023-03-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0014_expert_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expert",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos/%Y/%m/%d/"
            ),
        ),
    ]
