# Generated by Django 4.1.5 on 2023-06-16 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0019_forumquestion_forumanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumquestion',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Forum_category_question', to='pybo.category'),
        ),
    ]
