# Generated by Django 4.1.7 on 2023-06-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pybo", "0019_tanalyze_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="tanalyze",
            name="side_sephalo_line",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos/%Y/%m/%d/"
            ),
        ),
    ]
