# Generated by Django 4.1.5 on 2023-06-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0020_alter_forumquestion_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumquestion',
            name='forumimg',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
