# Generated by Django 4.1.6 on 2023-06-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0022_patientlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlist',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientlist',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientlist',
            name='progress',
            field=models.CharField(blank=True, choices=[('계측', '계측'), ('분석', '분석'), ('치료', '치료'), ('완료', '완료')], max_length=255, null=True),
        ),
    ]
