# Generated by Django 4.1.6 on 2023-06-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0023_alter_patientlist_birthday_alter_patientlist_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlist',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
