# Generated by Django 4.1.6 on 2023-07-04 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0023_image'),
        ('pybo', '0024_alter_patientlist_birthday'),
    ]

    operations = [
    ]
